- name: Create db
  mysql_db:
    name: bet
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock
    login_user: root
    login_password: "{{ root_password }}"

- name: Copy db dump file
  copy:
    src: bet.dmp
    dest: /tmp/

- name: Loading dump to master
  mysql_db:
    login_user: root
    login_password: "{{ root_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: bet
    state: import
    target: /tmp/bet.dmp

- name: Create user for replication
  mysql_user:
    name: repl
    host: '%'
    password: "{{ repl_password }}"
    login_user: root
    login_password: "{{ root_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    state: present
    priv: '*.*:REPLICATION SLAVE'

- name: Creating new dump
  shell: mysqldump --all-databases --add-drop-table --create-options --disable-keys \
                   --extended-insert --single-transaction --quick --events --routines \
                   --triggers --source-data=0 --skip-lock-tables --flush-privileges \
                   --ignore-table=bet.events_on_demand --ignore-table=bet.v_same_event \
                   -u root -p{{ root_password }} > /home/vagrant/master.sql
  args:
    creates: /home/vagrant/master.sql

- name: Copy dump file from master
  fetch:
    src: /home/vagrant/master.sql
    dest: files/master.sql
    flat: true